base_config: configs/training/hdn.yml

runs:
  - run_name: HDN_betaKL07_LR1e-06
    overrides:
      training.learning_rate: 0.000001

  - run_name: HDN_betaKL07_LR1e-05
    overrides:
      training.learning_rate: 0.00001

  - run_name: HDN_betaKL07_LR1e-04
    overrides:
      training.learning_rate: 0.0001
  
  - run_name: HDN_betaKL07_LR1e-03
    overrides:
      training.learning_rate: 0.001
