# =================================== #
# LISAI – Project-level configuration #
# =================================== #

project:
  name: lisai

paths:
  roots:
    data_dir: "{data_root}/Data"
    models_dir: "{data_root}/Models"
    noise_models_dir: "{data_root}/NoiseModels"
    # code_dir is injected automatically by Settings (project root)

  templates:
    dataset_registry: "{paths.roots.data_dir}/data_registry.yml"

    dataset_loading: "{paths.roots.data_dir}/{dataset_name}/{data_subfolder}"

    #run_dir = training dir, where checkpoints, training curves, validation images, etc. are saved
    run_dir: "{paths.roots.models_dir}/{dataset_name}/{models_subfolder}/{exp_name}" 

    tensorboard_runs_dir: "{paths.roots.code_dir}/tensorboard/{dataset_name}/{tensorboard_subfolder}"

    predictreal_saving: "{paths.roots.data_dir}/{dataset_name}/inference/{inference_subfolder}/{exp_name}"

    noise_model: "{paths.roots.noise_models_dir}/{noiseModel_name}/GMM.npz"

run_layout:
  subdirs:
    checkpoints: "checkpoints"
    validation_images: "validation_images"
    retrain_origin: "retrain_origin"

  artifacts:
    loss_file: "loss.txt"
    train_log: "train_log.log"
    config_train: "config_train.yaml"

  retrain_origin_artifacts:
    loss_file: "origin_loss.txt"
    train_log: "origin_log.log"
    config_train: "origin_config.yaml"

naming:
  exp_name_format: "{name}_{id:02d}"
  sample_id: "c{id:02d}"
