# yaml-language-server: $schema=../schema/preprocess.schema.json
dataset_name: "vim_fixed"
pipeline: "recon_mltpl_snr"
data_type: "recon"
fmt: "mltpl_snr"

pipeline_cfg:
  dump_subfolder: "timelapses_gathered"
  combine_subfolders: false
  crop_size: 1200
  gt_types: ["snr0","avg"]
  first_low_inp: true
  registration: true

log:
  enabled: true

split:
  enabled: true
  mode: "manual"
  random:
    seed: 0
    val_fraction: 0.1
    test_fraction: 0.1
  manual:
    match_by: "sample_id"
    val: ["c16"]
    test: ["c01","c14","c23"]
  reuse: null
