# yaml-language-server: $schema=../schema/experiment.schema.json
# ========================================================
# General experiment settings
# ========================================================
experiment:
  mode: train  # 'train'
  exp_name: CARE_noclip_mse
  overwrite: false # mainly for debug; to overwrite any exp_name with the same name
  post_training_inference: true

# ========================================================
# Paths
# ========================================================
routing:
  data_subfolder: "preprocess/recon"
  models_subfolder: "Denoising"
  tensorboard_subfolder: ""
  # used only for non-canonical loads => full path is used directly
  dataset_full_path: ""

# ========================================================
# Dataset / DataLoader configuration
# ========================================================
data:
  dataset_name: vim_fixed
  data_format: single
  canonical_load: true
  prep_before: true
  already_split: true
  filters:
    - tiff
    - tif

  paired: true
  target: "gt_avg" # for paired datasets
  input: "inp_single"

  patch_size: 128
  val_patch_size: 512
  batch_size: 64

  # options
  initial_crop: null
  augmentation: false
  patch_thresh: 0.15 # None or float [0,1]
  select_on_gt: false

normalization:
  norm_prm:
    clip: false

# ========================================================
# Model configuration
# ========================================================
model:
  architecture: unet
  parameters:
    feat: 64
    depth: 4
    in_channels: 1
    out_channels: 1
    activation: swish
    norm: group
    gr_norm: 8
    dropout: 0.1

# ========================================================
# Training configuration
# ========================================================
training:
  n_epochs: 100
  batch_size: 8
  learning_rate: 0.0001
  optimizer: Adam
  scheduler: ReduceLROnPlateau
  progress_bar: true
  debug_stop: false
  warmup:
    enabled: true
    steps: 500
    start_factor: 0.1
  auto_stop:
    enabled: true
    metrics: val_loss
    patience: 30

loss_function:
  name: MSE

# ========================================================
# Saving configuration
# ========================================================
saving:
  enabled: true
  canonical_save: true
  overwrite_best: true
  save_last: true
  entire_model: true
  state_dict: true
  validation_images: true
  validation_freq: 10  # save every Xth epoch

# ========================================================
# Tensorboard configuration
# ========================================================
tensorboard:
  enabled: false
  validation_images: true
